stages:
    - build
    - test
    - deploy

# ---------------- Partial Test on macOs10.12 ----------------

compile_macos:
    stage: build
    script:
        - git submodule update --init
        - cd keops/build
        - cmake ..
        - make -j2 VERBOSE=0
    tags:
        - macos10-12

test_macos_clang:
    stage: test
    script:
        - git submodule update --init
        - cd pykeops/test
        - /Users/ci/miniconda3/bin/python3 unit_tests_pytorch.py
        - /Users/ci/miniconda3/bin/python3 unit_tests_numpy.py
    tags:
        - clang
        - macos10-12
        - python3
    allow_failure: true

# ---------------- Partial Test on Ubuntu16.04 ----------------
compile_ubuntu_gcc:
    stage: build
    script:
        - git submodule update --init
        - cd keops/build
        - cmake ..
        - make -j2 VERBOSE=0
    tags:
        - gcc
        - ubuntu16.04

test_ubuntu_gcc:
    stage: test
    script:
        - git submodule update --init
        - cd pykeops/test
        - python3 unit_tests_pytorch.py
        - python3 unit_tests_numpy.py
    tags:
        - gcc
        - python3
        - ubuntu16.04


# ---------------- Full Test on Ubuntu16.04 ----------------
compile_ubuntu_cuda:
    stage: build
    script:
        - git submodule update --init
        - cd build/keops
        - cmake ..
        - make VERBOSE=0
    tags:
        - nvcc
        - ubuntu16.04
                
          
test_ubuntu_cuda:
    stage: test
    script:
        - git submodule update --init
        - cd pykeops/test
        - python3 unit_tests_pytorch.py
        - python3 unit_tests_numpy.py
        - cd ../../keopslab/test
        - export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6;matlab -nodisplay -r "r=runtests('generic_test.m'),exit(sum([r(:).Failed]))"
    tags:
        - matlab
        - nvcc
        - python3
        - ubuntu16.04
