stages:
    - build
    - test
    - deploy

# ---------------- Partial Test on macOs10.12 ----------------

compile_macos:
    stage: build
    script:
        - cd build
        - cmake ../keops
        - make -j2 VERBOSE=0
    tags:
        - macos10-12


# ---------------- Partial Test on Ubuntu16.04 ----------------
compile_ubuntu_gcc:
    stage: build
    script:
        - cd build
        - cmake ../keops
        - make VERBOSE=0
    tags:
        - gcc
        - ubuntu16.04

test_ubuntu_gcc:
    stage: test
    script:
        - cd pykeops/test
        - python3 unit_tests_pytorch.py
    tags:
        - gcc
        - python3
        - ubuntu16.04


# ---------------- Full Test on Ubuntu16.04 ----------------
compile_ubuntu_cuda:
    stage: build
    script:
        - cd build
        - cmake ../keops
        - make VERBOSE=0
    tags:
        - nvcc
        - ubuntu16.04
                
          
test_ubuntu_cuda:
    stage: test
    script:
        - cd pykeops/test
        - python3 unit_tests_pytorch.py
        - python3 unit_tests_numpy.py
        - cd ../../keopslab/test
        - matlabnd -r "r=runtests('generic_test.m');exit(sum([r(:).Failed]))"
    tags:
        - matlab
        - nvcc
        - python3
        - ubuntu16.04
